config/routes.rb
Rails.application.routes.draw do
  devise_for :profiles
  root to: 'profiles#index'
  resources :profiles

  resources :games, except: [:show] do
    get ':my_class' => 'games#my_class', as: :games_my_class, on: :collection
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  validates_presence_of :my_class, :opp_class, :result, :type_of_a_game

  belongs_to :profile

  alias_attribute :user_id, :profile_id

  extend Enumerize
  enumerize :my_class, in: [:mage, :hunter, :rogue, :warrior, :druid, :warlock, :shaman, :priest, :paladin]
  enumerize :opp_class, in: [:mage, :hunter, :rogue, :warrior, :druid, :warlock, :shaman, :priest, :paladin]
  enumerize :result, in: [:win, :lose]
  enumerize :type_of_a_game, in: [:arena, :ranked, :casual]

  has_attached_file :screenshot, :styles => { :medium => "500x500>", :thumb => "300x300>"  },
    :default_url => "/images/:style/missing.png", :storage => :elvfs, :elvfs_url => Settings['storage.url']

  validates_attachment_content_type :screenshot, :content_type => /\Aimage\/.*\Z/

  searchable do
    string :my_class
    string :opp_class
    string :result
    string :type_of_a_game

    integer :user_id
    integer :id
  end
end

# == Schema Information
#
# Table name: games
#
#  id                      :integer          not null, primary key
#  my_class                :string
#  opp_class               :string
#  result                  :string
#  created_at              :datetime
#  updated_at              :datetime
#  type_of_a_game          :string
#  stat                    :string
#  user_id                 :integer
#  comment                 :text
#  screenshot_file_name    :string
#  screenshot_content_type :string
#  screenshot_file_size    :integer
#  screenshot_updated_at   :datetime
#  screenshot_url          :text
#

app/models/profile.rb
class Profile < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :games
end

# == Schema Information
#
# Table name: profiles
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime
#  updated_at             :datetime
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_profile!
  skip_before_filter :verify_authenticity_token

  helper_method :page, :per

  def index
    @games = current_profile.games.search { paginate page: 1, per_page: Game.count; order_by(:id, :desc) }.results
    @games_for_index = current_profile.games.search { paginate page: page, per_page: per; order_by(:id, :desc) }.results
  end

  def new
    @game = Game.new
  end

  def create
    if current_profile
      @game = current_profile.games.create(game_params) #Game.new(game_params.merge(user_id: current_profile.id))
      if @game
        render nothing: true, status: 200 and return if request.xhr?

        redirect_to root_path
      else
        render 'new'
      end
    end
  end

  def update
    Game.find(params[:id]).update(game_params) and redirect_to games_path
  end

  def edit
    @game = Game.find(params[:id])
  end

  def my_class
    @games = Game.where(my_class: params[:my_class], user_id: current_profile.id).order('id desc').page(page).per(per)
  end

  def destroy
    Game.find(params[:id]).destroy
    redirect_to games_path
  end

  def page
    params[:page] || 1
  end

  def per
    20
  end

  private

  def game_params
    params.require(:game).permit(:my_class, :opp_class, :type_of_a_game, :result, :comment, :screenshot)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  include ApplicationHelper

  helper_method :math_stat, :win_stat, :lose_stat

  before_action :authenticate_profile!

  def index
    @games = Game.search { with :user_id, current_profile.id; paginate page: 1, per_page: Game.count }.results

    @game = Game.new

    @unique_classes = @games.map(&:my_class).uniq
    @last_game = Game.where(user_id: current_profile.id).last
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def percentages(win, all, precision = 1)
    number_to_percentage((win / all) * 100, precision: precision)
  end

  def percentages_for_stat(stat, precision = 1)
    number_to_percentage(stat, precision: precision)
  end

  def math_stat(my_class, opp_class, type)
    all_games = current_profile.games.search { with :my_class, my_class; with :opp_class, opp_class; with :type_of_a_game, type; paginate page: 1, per_page: Game.count }.results.count
    win_games = Game.where(my_class: my_class, opp_class: opp_class, type_of_a_game: type, result: 'win', user_id: current_profile.id).count
    (win_games.to_f / all_games.to_f) * 100
  end

  def win_stat
    current_profile.games.search { with :result, 'win'; paginate page: 1, per_page: Game.count }.results.count
  end

  def lose_stat
    current_profile.games.search { with :result, 'lose'; paginate page: 1, per_page: Game.count }.results.count
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/commons/_form.html.erb
<%= simple_form_for @game, remote: true do |f| %>
  <%= f.input :my_class, selected: Game.where(user_id: current_profile.id).last.try(:my_class) %>
  <%= f.input :opp_class, selected: Game.where(user_id: current_profile.id).last.try(:opp_class) %>
  <%= f.input :type_of_a_game, as: :radio_buttons, checked: Game.where(user_id: current_profile.id).last.try(:type_of_a_game) %>
  <%= f.input :result, as: :radio_buttons, checked: Game.where(user_id: current_profile.id).last.try(:result) %>
  <%= f.input :comment, as: :text, input_html: { size: '40x10' } %>
  <%= f.input :screenshot %>
  <%= f.submit 'Создать', class: 'btn btn-normal' %> <%= image_tag 'loading.gif', :class => 'loading js-loading' %> <%= image_tag 'ok.gif', :class => 'ok js-ok' %>
<% end %>

app/views/games/_table.html.erb
<table>
  <thead>
    <th>Мой класс</th>
    <th>Класс противника</th>
    <th>Тип</th>
    <th>Результат</th>
    <th>Винрейт</th>
    <th>Дата</th>
    <th>Комментарий</th>
    <th></th>
  </thead>
  <tbody>
    <% @games_for_index.each do |game| %>
      <tr>
        <td><%= link_to t(game.my_class), games_my_class_games_path(game.my_class) %></td>
        <td><%= t(game.opp_class) %></td>
        <td><%= t(game.type_of_a_game) %></td>
        <td><%= t(game.result) %></td>
        <td><%= percentages_for_stat(math_stat(game.my_class, game.opp_class, game.type_of_a_game)) %></td>
        <td><%= time_ago_in_words(game.created_at) %> назад</td>
        <td><%= game.comment if game.comment.present? %> <br /> <%= link_to 'Скриншот', game.try(:screenshot_url), target: '_blank' if game.screenshot.present? %></td>
        <td>
          <%= link_to 'Редактировать', edit_game_path(game) %>
          <%= link_to 'Удалить', game_path(game), method: :delete, data: { confirm: 'Точно удалить?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @games_for_index %>

app/views/games/edit.html.erb
<%= render 'commons/form' %>

app/views/games/index.html.erb
<% unless profile_signed_in? %>
  <%= link_to 'Войти', new_profile_session_path %> или <%= link_to 'Зарегистрироваться', new_profile_registration_path %>
<% end %>

<%= render partial: 'table' %>

app/views/games/my_class.html.erb
<%= render partial: 'table' %>

app/views/games/new.html.erb
<%= render 'commons/form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Статистика игр в HeartStone. <%= "Пользователь: #{current_profile.email}" if profile_signed_in? %></title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>
  <body>
    <%= render partial: 'header/header' %>
    <div class="wrapper">
      <div class='fixed_left_menu'>
        <ul>
          <% if controller_name == 'games' %>
            <li><%= link_to 'Профиль', profiles_path %></li>
          <% else %>
            <li><%= link_to 'Все игры', games_path %></li>
          <% end %>
          <li><%= link_to 'Выход', destroy_profile_session_path, method: :delete, data: { confirm: 'Точно?' } %></li>
        </ul>
      </div>

      <% if profile_signed_in? && @games.present? %>
        <div class="menu">
          <ul>
            <li>Общий показатель: <%= percentages(win_stat, @games.count.to_f) %></li>
            <li>Поражений: <%= lose_stat %></li>
            <li>Побед: <%= win_stat %></li>
            <li>Всего игр: <%= @games.count %></li>
          </ul>
        </div>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/profiles/index.html.erb
<div class='form js-form'>
  <%= render 'commons/form' %>
</div>

<div class='last_game'>
  <% if @last_game %>
    Последняя игра:  <%= link_to I18n.t(@last_game.my_class), games_my_class_games_path(@last_game.my_class) %> против <b><%= I18n.t(@last_game.opp_class) %>а</b>, результат: <b><%= I18n.t(@last_game.result) %></b>, режим: <b><%= I18n.t(@last_game.type_of_a_game) %></b>, <%= time_ago_in_words(@last_game.created_at) %> назад
  <% end %>
</div>

<% @unique_classes.each do |my_class| %>
  <div class="hero">
    <div class="hero_title">
      <%= link_to I18n.t(my_class), games_my_class_games_path(my_class) %>
    </div>
    <div class="info">
      <ul>
        <li>Всего игр: <%= Game.where(my_class: "#{my_class}", user_id: current_profile.id).count %></li>
        <li>Побед: <%= Game.where(my_class: "#{my_class}", result: :win, user_id: current_profile.id).count %></li>
        <li>Поражений: <%= Game.where(my_class: "#{my_class}", result: :lose, user_id: current_profile.id).count %></li>
        <li>Показатель: <%= percentages(Game.where(my_class: "#{my_class}", result: :win, user_id: current_profile.id).count.to_f, Game.where(my_class: "#{my_class}", user_id: current_profile.id).count.to_f) %></li>
      </ul>
    </div>
  </div>
<% end %>